### ISSUE TITLE
Package sync: Error fetch pkg

### ISSUE THREAD

**Issue by renlite** [onyx-lang/onyx#100] opened 2024-01-22 13:16 UTC
Trying to install lsp, I get this error on Win10/Onyx Nightly Release 20240118:
```
PS C:\Onyx\onyx-lsp-main> onyx package sync
       ←[32mFetch  ←[39mhttp://github.com/onyx-lang/pkg-json-rpc  0.0.30
FAILED TO CREATE PROCESS: 2
FAILED TO CREATE PROCESS: 2
FAILED TO CREATE PROCESS: 2
FAILED TO CREATE PROCESS: 2
←[0m←[31m       Error  ←[39mFailed to fetch http://github.com/onyx-lang/pkg-json-rpc version 0.0.30.
←[0m←[31m       Error  ←[39mAborting sync.
←[0m
```
The version 0.0.30 is on Github.

**Comment by brendanfh** [comment] 2024-01-31 15:04
Sorry for not getting back to you on this issue sooner! I see you are using the Windows of Onyx, which I sadly do not get to test very often as I primarily use a Linux laptop. That being said, I *think* this issue is because it could not find a `git.exe` executable to download the dependencies for the LSP. I know the way that this process works on Windows is not entirely correct, so I will leave this open until I address that root cause.

In the meantime if you want to have a slightly better experience with Onyx on Windows, I would recommend using WSL and installing Onyx there. Stay tuned for a fix!

**Comment by brendanfh** [comment] 2024-03-04 15:20
I believe with recent changes, the LSP and package manager work much better on Windows. I have tested installing the LSP on a fresh install of Windows with the newest nightly version and it worked flawlessly.

I am going to close this issue, but if the issue persists feel free to necro-bump this issue or make a new issue.

**Closed by brendanfh** 2024-03-04 15:20 UTC
Labels: bug
